config/routes.rb
RailsInterviewProblem::Application.routes.draw do
  root :to => 'articles#index'
  resources :articles do
      resources :comments
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
   attr_accessible :published, :author, :content, :url, :title

  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
   attr_accessible :content, :article_id
 
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
   	feeds = Feedjira::Feed.fetch_and_parse("http://feedjira.com/blog/feed.xml") # returns a Hash, with each url having a Feedjira::Feed object
      feeds.entries.each do |art|
        article=Article.where(:title=>art.title).first
        article=Article.create(:published=>art.published,:author=>art.author,:content=>art.content,:url=>art.url,:title=>art.title) if article.nil?
      end

    @articles=Article.order("created_at desc").paginate(:page => params[:page], :per_page => 10)
  end

  def show
     @article=Article.find(params[:id])
     @comments = @article.comments
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 
  def new
    @article=Article.find(params[:article_id])
    @comment=Comment.new
    @comments = @article.comments
  end

 def create
    @article=Article.find(params[:article_id])
    @comments = @article.comments
    @comment = Comment.new(params[:comment])
    @comment.article_id=@article.id
    respond_to do |format|
      if @comment.save
        format.js 
      else
        format.js { render js: "bad" }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_article_text.html.erb
<%=strip_tags(@article.content)%></br>
<%=link_to "Comments", new_article_comment_path(@article) , :remote => true%>
<div id="comment_<%=@article.id%>" class="comment_pop" style="display:none;"></div>

app/views/articles/index.html.erb
<div class="page_content">
  <h2>Wired Top Stories</h2>
  <% @articles.each do |article| %>
    <p>
      <%= link_to article.title ,article, :remote => true%><br/>
      <%= article.published%>
    </p>
    <p>    
      <div id="content_<%=article.id%>"></div>
    </p> 
  <%end%>
  <div class="pagenation">
    <%=  will_paginate @articles%>
  </div>
</div>

app/views/articles/show.js.erb
$('#content_<%=@article.id%>').html("<%= escape_javascript(render(:partial => "article_text"))%>");

app/views/comments/_form.html.erb
<div class="gap"><a href="javascript:void(0)" class="close_comment"><%= image_tag "close_popup.png"%></a></div>
<div id="com_for_<%=@article.id%>">
 <%=render :partial=>"index"%>
</div>
<%= form_for([@article,@comment], :remote => true) do |f| %>

  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%="Add Comment"%></br>
    <%= f.text_area :content , :rows=>2, :cols=>45%>
     
  </div>
  
  <div class="actions">
    <%= f.submit "Comment"%>
  </div>
<% end %>
<script>
$(document).ready(function(){
    $('.close_comment').click(function(){
        $('#comment_<%=@article.id%>').hide();
    });
});
</script>

app/views/comments/_index.html.erb
Listing <b><%= @comments.size %></b> comments<br/>
<%@comments.each do |comment|%>
  <span class="show_content">
    <%= comment.content%> - at <%= comment.created_at.strftime("%d %b %Y - %H:%m") %></br>
  </span>
<%end%>

app/views/comments/create.js.erb
$('#comment_content').val("");
$("#com_for_<%=@article.id%>").html("<%= escape_javascript(render(:partial => "index", :object => @comments))%>");
 

app/views/comments/new.js.erb
$("#comment_<%=@article.id%>").html("<%= escape_javascript(render(:partial => "form"))%>");
$("#comment_<%=@article.id%>").show();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsInterviewProblem</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<center class="spinner">
 <%= image_tag "ajax-loader.gif" %>
</center>

</body>
</html>